version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.18.2
    restart: on-failure:0
    ports:
     - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/data"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ./data/semantic_filters_data/weaviate_data:/data
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    environment:
      ENABLE_CUDA: 0
  yaserviceru:
    build:
      context: .
      dockerfile: Dockerfile
    #image: osuzdalev/yaserviceru:latest
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - weaviate