version: '3.4'
services:
  database:
    image: "postgres:15.3"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD} # for the docker, in the code standard naming "DATABASE_*"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ${DATABASE_DATA}:/var/lib/postgresql/data # The database. This will increase in size with time. !!! DON'T COMMIT !!!
      - ${DATABASE_CONFIG}:/etc/postgresql/ # The config files. !!! DON'T COMMIT !!!
    command: postgres -c config_file=/etc/postgresql/postgres.conf

  weaviate:
    image: semitechnologies/weaviate:1.9.1
    restart: unless-stopped
    ports:
     - "${WEAVIATE_PORT}:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: ${WEAVIATE_PERSISTENCE}
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ${WEAVIATE_DATA}:/data
    depends_on:
      - t2v-transformers

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    restart: unless-stopped
    environment:
      ENABLE_CUDA: 0
      # NVIDIA_VISIBLE_DEVICES: all # enable if running with CUDA

  yaserviceru:
    build:
      context: .
      dockerfile: Dockerfile
    #image: ${APP_IMAGE}
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_LOGS}:/app/${APP_LOGS}
      - ${APP_PERSISTENCE}:/app/${APP_PERSISTENCE}
    depends_on:
      - database
      - weaviate
      - t2v-transformers