from setuptools import setup, find_packages

# Load the README file
with open("README.md", "r") as file:
    long_description = file.read()

setup(
    name="yaserviceru",
    version="0.2.18",
    author="Oleg Souzdalev",
    author_email="odsuzdalev@gmail.com",
    description="Yaserviceru is a bot application",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/osuzdalev/yaserviceru",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Natural Language :: English",
        "Programming Language :: Python :: 3.9",
    ],
    python_requires=">=3.9",
    entry_points={
        "console_scripts": [
            "yaserviceru=yaserviceru.__main__:main",
        ],
    },
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "aiohttp",
        "aiosignal",
        "anyio",
        "APScheduler",
        "argcomplete",
        "astroid",
        "async-timeout",
        "attrs",
        "Authlib",
        "black",
        "build",
        "cachetools",
        "certifi",
        "cffi",
        "charset-normalizer",
        "click",
        "cryptography",
        "decorator",
        "dill",
        "docutils",
        "exceptiongroup",
        "filelock",
        "frozenlist",
        "fsspec",
        "h11",
        "httpcore",
        "httpx",
        "huggingface-hub",
        "idna",
        "importlib-metadata",
        "isort",
        "jaraco.classes",
        "Jinja2",
        "joblib",
        "keyring",
        "markdown-it-py",
        "MarkupSafe",
        "mccabe",
        "mdurl",
        "more-itertools",
        "mpmath",
        "multidict",
        "mypy-extensions",
        "networkx",
        "nh3",
        "nltk",
        "numpy",
        "openai",
        "packaging",
        "pandas",
        "pathspec",
        "Pillow",
        "pkginfo",
        "platformdirs",
        "psycopg",
        "psycopg-binary",
        "psycopg-c",
        "psycopg-pool",
        "pyaes",
        "pyasn1",
        "pycparser",
        "Pygments",
        "pylint",
        "pyproject_hooks",
        "python-dateutil",
        "python-dotenv",
        "python-telegram-bot",
        "pytz",
        "PyYAML",
        "readme-renderer",
        "regex",
        "requests",
        "requests-toolbelt",
        "rfc3986",
        "rich",
        "rsa",
        "ruff",
        "safetensors",
        "scikit-learn",
        "scipy",
        "sentence-transformers",
        "sentencepiece",
        "six",
        "sniffio",
        "sympy",
        "Telethon",
        "threadpoolctl",
        "tiktoken",
        "tokenizers",
        "tomli",
        "tomlkit",
        "torch",
        "torchvision",
        "tqdm",
        "transformers",
        "twine",
        "typing_extensions",
        "tzlocal",
        "urllib3",
        "validators",
        "weaviate-client",
        "xmltodict",
        "yarl",
        "yq",
        "zipp",
    ],
)
