chatgpt:
  handler_name: ChatGptHandler
  location: src.command.client.chatgpt.handler
  command:
    - "/chat"
    - "/chat_stop"
    - "/pay"
  message:
    - "🤖Чат с подержкой"
    - "CONFIRM_CHATGPT_PAYMENT"
    - "DECLINE_CHATGPT_PAYMENT"