# command
start:
  handler_name: StartHandler
  location: src.command.client.start.handler
  command:
    - "start"

#wiki:
#  handler_name: WikiHandler
#  location: src.command.client.wiki.handler
#  command:
#    - "wiki"
#    - "cancel"
#  message:
#    - "📖Справочник"
#    - "❌Отменить"

# common
error_logging:
  handler_name: ErrorHandler
  location: src.common.error_logging.handler

global_fallback:
  handler_name: GlobalFallbackHandler
  location: src.common.global_fallback.handler

# database
database:
  handler_name: CollectorHandler
  location: src.database.handler