# All the different addresses / URL
# TODO Investigate using a database to structure and manage the data (wiki or otherwise)

Apple: !include /app/telefix/media/user/wiki/Apple/Apple.yaml

A_Mac: !include /app/telefix/media/user/wiki/Apple/Mac/Mac.yaml

A_M_Slowing_Bugging: !include /app/telefix/media/user/wiki/Apple/Mac/1_Slowing_Bugging/Slowing_Bugging.yaml

A_M_SB_Reset_CMOS_NVRAM: !include /app/telefix/media/user/wiki/Apple/Mac/1_Slowing_Bugging/Reset_CMOS_NVRAM/Reset_CMOS_NVRAM.yaml

# ======================================================================================================================

A_M_Installation_Recovery: !include /app/telefix/media/user/wiki/Apple/Mac/2_Installation_Recovery/Installation_Recovery.yaml

A_M_IR_Update_MacOS: !include /app/telefix/media/user/wiki/Apple/Mac/2_Installation_Recovery/Update_MacOS/Update_MacOS.yaml
A_M_IR_Recovery_MacOS: !include /app/telefix/media/user/wiki/Apple/Mac/2_Installation_Recovery/Recovery_MacOS/Recovery_MacOS.yaml
A_M_IR_Installation_BootUSB: !include /app/telefix/media/user/wiki/Apple/Mac/2_Installation_Recovery/Installation_BootUSB/Installation_BootUSB.yaml

# ======================================================================================================================

A_M_Bootcamp_Parallels: !include /app/telefix/media/user/wiki/Apple/Mac/3_Bootcamp_Parallels/Bootcamp_Parallels.yaml

A_M_BP_Bootcamp: !include /app/telefix/media/user/wiki/Apple/Mac/3_Bootcamp_Parallels/Bootcamp/Bootcamp.yaml

# ======================================================================================================================

A_M_Devices_Periphery: !include /app/telefix/media/user/wiki/Apple/Mac/4_Devices_Periphery/Devices_Periphery.yaml

A_M_DP_Flash_Drive: !include /app/telefix/media/user/wiki/Apple/Mac/4_Devices_Periphery/Flash_Drive/Flash_Drive.yaml

# ======================================================================================================================

A_M_System_Settings: !include /app/telefix/media/user/wiki/Apple/Mac/5_System_Settings/System_Settings.yaml

A_M_SS_Language_Input: !include /app/telefix/media/user/wiki/Apple/Mac/5_System_Settings/Language_Input/Language_Input.yaml

# ======================================================================================================================

A_M_Saving_Data: !include /app/telefix/media/user/wiki/Apple/Mac/6_Saving_Data/Saving_Data.yaml

A_M_SD_Free_Storage: !include /app/telefix/media/user/wiki/Apple/Mac/6_Saving_Data/Free_Storage/Free_Storage.yaml

# ======================================================================================================================

A_M_Network_Internet: !include /app/telefix/media/user/wiki/Apple/Mac/7_Network_Internet/Network_Internet.yaml

A_M_NI_Reset_Network_Settings: !include /app/telefix/media/user/wiki/Apple/Mac/7_Network_Internet/Reset_Network_Settings/Reset_Network_Settings.yaml

# ======================================================================================================================

A_M_Security: !include /app/telefix/media/user/wiki/Apple/Mac/8_Security/Security.yaml

A_M_S_Authorize_Installation_Apps: !include /app/telefix/media/user/wiki/Apple/Mac/8_Security/Authorize_Installation_Apps/Authorize_Installation_Apps.yaml

# ======================================================================================================================

A_M_Display_Graphics: !include /app/telefix/media/user/wiki/Apple/Mac/9_Display_Graphics/Display_Graphics.yaml

A_M_DG_Automatic_Switching: !include /app/telefix/media/user/wiki/Apple/Mac/9_Display_Graphics/Automatic_Switching/Automatic_Switching.yaml

# ======================================================================================================================

A_M_Terminal: !include /app/telefix/media/user/wiki/Apple/Mac/10_Terminal/Terminal.yaml

A_M_T_Date_Time: !include /app/telefix/media/user/wiki/Apple/Mac/10_Terminal/Date_Time/Date_Time.yaml

A_M_T_Launch_Terminal: !include /app/telefix/media/user/wiki/Apple/Mac/10_Terminal/Launch/Launch.yaml

A_M_T_Fusion_Drive: !include /app/telefix/media/user/wiki/Apple/Mac/10_Terminal/Fusion_Drive/Fusion_Drive.yaml
A_M_T_FD_High_Sierra_Plus: !include /app/telefix/media/user/wiki/Apple/Mac/10_Terminal/Fusion_Drive/High_Sierra_Plus/High_Sierra_Plus.yaml
A_M_T_FD_Mojave_Minus: !include /app/telefix/media/user/wiki/Apple/Mac/10_Terminal/Fusion_Drive/Mojave_Minus/Mojave_Minus.yaml


# ######################################################################################################################


Windows: !include /app/telefix/media/user/wiki/Windows/Windows.yaml

# ======================================================================================================================

W_Slowing_Bugging: !include /app/telefix/media/user/wiki/Windows/1_Slowing_Bugging/Slowing_Bugging.yaml

W_SB_Auto_Upload: !include /app/telefix/media/user/wiki/Windows/1_Slowing_Bugging/Auto_Upload/Auto_Upload.yaml
W_SB_Heating: !include /app/telefix/media/user/wiki/Windows/1_Slowing_Bugging/Heating/Heating.yaml
W_SB_Hard_Disk_SSD: !include /app/telefix/media/user/wiki/Windows/1_Slowing_Bugging/Hard_Disk_SSD/Hard_Disk_SSD.yaml

# ======================================================================================================================

W_Update_Drivers: !include /app/telefix/media/user/wiki/Windows/2_Update_Drivers/Update_Drivers.yaml

W_UD_Update_Windows_10_11: !include /app/telefix/media/user/wiki/Windows/2_Update_Drivers/Update_Windows_10_11/Update_Windows_10_11.yaml
W_UD_Disable_Update: !include /app/telefix/media/user/wiki/Windows/2_Update_Drivers/Disable_Update/Disable_Update.yaml
W_UD_Installing_Updating_Drivers: !include /app/telefix/media/user/wiki/Windows/2_Update_Drivers/Installing_Updating_Drivers/Installing_Updating_Drivers.yaml

# ======================================================================================================================

W_Installation_Recovery: !include /app/telefix/media/user/wiki/Windows/3_Installation_Recovery/Installation_Recovery.yaml

W_IR_Bootable_USB: !include /app/telefix/media/user/wiki/Windows/3_Installation_Recovery/Bootable_USB/Bootable_USB.yaml
W_IR_No_Disk_Partitions: !include /app/telefix/media/user/wiki/Windows/3_Installation_Recovery/No_Disk_Partitions/No_Disk_Partitions.yaml
W_IR_OS_Installation: !include /app/telefix/media/user/wiki/Windows/3_Installation_Recovery/OS_Installation/OS_Installation.yaml

# ======================================================================================================================

W_Switch_Charge: !include /app/telefix/media/user/wiki/Windows/4_Switch_Charge/Switch_Charge.yaml

W_SC_No_Info: !include /app/telefix/media/user/wiki/Windows/4_Switch_Charge/No_Info/No_Info.yaml

# ======================================================================================================================

W_Network_Internet: !include /app/telefix/media/user/wiki/Windows/5_Network_Internet/Network_Internet.yaml

W_NI_No_Internet_Access: !include /app/telefix/media/user/wiki/Windows/5_Network_Internet/No_Internet_Access/No_Internet_Access.yaml

# ======================================================================================================================

W_Devices_Periphery: !include /app/telefix/media/user/wiki/Windows/6_Devices_Periphery/Devices_Periphery.yaml

# ======================================================================================================================

W_Display_Graphics: !include /app/telefix/media/user/wiki/Windows/7_Display_Graphics/Display_Graphics.yaml

W_DG_No_Info: !include /app/telefix/media/user/wiki/Windows/7_Display_Graphics/No_Info/No_Info.yaml

# ======================================================================================================================

W_System_Settings: !include /app/telefix/media/user/wiki/Windows/8_System_Settings/System_Settings.yaml

W_SS_No_Info: !include /app/telefix/media/user/wiki/Windows/8_System_Settings/No_Info/No_Info.yaml

# ======================================================================================================================

W_Saving_Data: !include /app/telefix/media/user/wiki/Windows/9_Saving_Data/Saving_Data.yaml

W_SD_Clearing_Disk: !include /app/telefix/media/user/wiki/Windows/9_Saving_Data/Clearing_Disk/Clearing_Disk.yaml

# ======================================================================================================================

W_BIOS: !include /app/telefix/media/user/wiki/Windows/10_BIOS/BIOS.yaml

W_B_Change_Boot_Params: !include /app/telefix/media/user/wiki/Windows/10_BIOS/Change_Boot_Params/Change_Boot_Params.yaml