version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.18.2
    restart: on-failure:0
    ports:
     - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/data" # Updated persistence data path
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - /home/yaserviceru/Desktop/YaServiceRu/clientcommands/chatgpt_module/Weaviate/data:/data # Added shared volume
      #- /home/yaserviceru/Desktop/YaServiceRu/clientcommands/chatgpt_module/Weaviate/data:/data
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2 # Multilinguil model
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable