name: dev

common:
  telegram_id:
    bot: 6083336654
    yaserviceru_center: 6211181238
    dev: 5278871996
    contractor: 247648076
  telegram_username:
    bot: YaServiceRuDevBot
  email:
    yaserviceru: ruyaservice@yandex.ru
    dev: odsuzdalev@yandex.ru
    contractor: yanisbrothers@yandex.ru

technical:
  filepath:
    persistence: data/app/persistence
    logger: data/app/logs.log
  api_weaviate: http://localhost:8080 # local or docker
  database_postgres:
    host: localhost # local or docker
    db: postgres
    user: postgres
    post: 5432

secret:
  api_openai: API_OPENAI
  token_telegram: TOKEN_TG_DEV_BOT
  token_payment_provider: TOKEN_PAYMENT_PROVIDER_YOOKASSA_TEST
  database_password: DATABASE_POSTGRES_PASSWORD
  password_yaserviceru_app: PASSWORD_YANDEX_YASERVICERU_APP