name: dev

yaserviceru:
  app:
    tg_id:
      bot: 6083336654
      admin: 6211181238
      dev: 5278871996
      contractor: 247648076
    tg_username:
      bot: YaServiceRuDevBot
    email:
      admin: ruyaservice@yandex.ru
      dev: odsuzdalev@yandex.ru
      contractor: yanisbrothers@yandex.ru
      smtp:
        url: smtp.yandex.ru
        port: 587
  network:
    images: osuzdalev/yaserviceru:beta
    port: 8081
    persistence: ./data/app/persistence
    logs: ./data/app/logs.log
  secret:
    api_openai: API_OPENAI
    token_telegram: TOKEN_TG_DEV_BOT
    token_payment_provider: TOKEN_PAYMENT_PROVIDER_YOOKASSA_TEST
    password_smtp: PASSWORD_YANDEX_YASERVICERU_APP

database:
  host: localhost # local or docker
  dbname: postgres
  user: postgres
  port: 5432
  data: ../data/database/pg_data
  config: ../data/database/pg_config
  secret:
    password: DATABASE_POSTGRES_PASSWORD

weaviate:
  api: http://localhost:8080 # local or docker
  port: 8080
  data: ../data/vector_database/embeddings # for the volumes
  persistence: /var/lib/data # path inside the docker
