name: core

telefix:
  contact:
    tg_id:
      bot: 5854999777
      admin: 6211181238
      dev: 178716280
      contractor: 247648076
    tg_username:
      bot: YaServiceRuBot
    email:
      admin: ruyaservice@yandex.ru
      dev: odsuzdalev@yandex.ru
      contractor: yanisbrothers@yandex.ru
      smtp:
        url: smtp.yandex.ru
        port: 587
  persistence: /Users/osuz/PycharmProjects/YaServiceRu/app/storage/main.pkl
  logs: /Users/osuz/PycharmProjects/YaServiceRu/app/log/main.log
  docker:
    port: 8081
  secret:
    api_openai: API_OPENAI
    token_telegram: TOKEN_TG_DEV_BOT
    token_payment_provider: TOKEN_PAYMENT_PROVIDER_YOOKASSA_TEST
    password_smtp: PASSWORD_YANDEX_YASERVICERU_APP