name: main

common:
  telegram_id:
    bot: 5854999777
    yaserviceru_center: 6211181238
    dev: 178716280
    contractor: 247648076
  telegram_username:
    bot: YaServiceRuBot
  email:
    yaserviceru: ruyaservice@yandex.ru
    dev: odsuzdalev@yandex.ru
    contractor: yanisbrothers@yandex.ru

technical:
  filepath:
    persistence: data_reader/app/persistence.pkl
    logger: data_reader/app/logs.log
  api_weaviate: http://localhost:8080 # local or docker
  database_postgres:
    host: localhost # local or docker
    db: postgres
    user: postgres
    post: 5432

secret:
  api_openai: API_OPENAI
  token_telegram: TOKEN_TG_MAIN_BOT
  token_payment_provider: TOKEN_PAYMENT_PROVIDER_YOOKASSA
  database_password: DATABASE_POSTGRES_PASSWORD
  password_yaserviceru_app: PASSWORD_YANDEX_YASERVICERU_APP